parameters:
- name: deploySteps # the name of the parameter is deploySteps
  type: stepList # data type is StepList
  default: [] # default value of deploySteps

resources:
  containers:
    - container: wincontainer
      image: mcr.microsoft.com/windows/servercore:ltsc2019      

stages:
- stage: secure_deploy
  pool:
    vmImage: windows-latest
  jobs:
  - job: secure_deploy
    container: wincontainer
    steps:
    - ${{ each step in parameters.deploySteps }}:
      - ${{ each pair in step }}:
          ${{ if ne(pair.key, 'target') }}:
            ${{ pair.key }}: ${{ pair.value }}
