parameters:
  azureServiceConnection: ''
  resourceGroupName: ''
  environment: ''

jobs:
- deployment: Deploy
  displayName: Deploy
  environment: ${{ parameters.environment }}
  strategy:
    runOnce:
      deploy:
        steps:
        - task: AzurePowerShell@5
          displayName: 'Azure Powershell Test'
          inputs:
            azureSubscription: ${{ parameters.azureServiceConnection }}
            ScriptType: InlineScript
            azurePowerShellVersion: LatestVersion
            pwsh: true
            Inline: |
              Get-AzContext