parameters:
  jobName: Deploy

jobs:
- job: ${{ parameters.jobName }}
  displayName: ${{ parameters.jobName }}

  steps:
  - checkout: self
  - script: echo $(azureServiceConnection)

# replace the above with your deploymennt job
# - deployment: ${{ parameters.jobName }}
#   displayName: ${{ parameters.jobName }}
#   pool: ...
#   environment: this can come in as a parameters to this temmplate
#   ...
#   steps:
#   - ...
