parameters:
  jobName: Deploy

jobs:
- deployment: ${{ parameters.jobName }}
  displayName: ${{ parameters.jobName }}
  environment: $(environment)
  strategy:
    runOnce:
      deploy:
        steps:
        - task: AzurePowerShell@5
          displayName: 'Azure Powershell Test'
          inputs:
            azureSubscription: $(azureServiceConnection)
            ScriptType: InlineScript
            azurePowerShellVersion: LatestVersion
            pwsh: true
            Inline: |
              Get-AzContext