variables:
  system.debug: true

stages:
- stage: CI
  displayName: 'Deploy To CI'

  jobs:
  - template: deploymentJob.yml
    parameters:
    - jobName: Deploy
    - template: parameters/ci.yml

- stage: QA
  displayName: 'Deploy To QA'
  
  jobs:
  - template: deploymentJob.yml
    parameters:
    - jobName: Deploy
    - template: parameters/qa.yml
