variables:
  system.debug: true

stages:
- stage: CI
  displayName: 'Deploy To CI'
  jobs:
  - template: environments/ci.yml

- stage: QA
  displayName: 'Deploy To QA'
  jobs:
  - template: environments/qa.yml
