variables:
  system.debug: true

stages:
- stage: CI
  displayName: 'Deploy To CI'
  variables:
  - template: variables/ci.yml

  jobs:
  - template: deploymentJob.yml

- stage: QA
  displayName: 'Deploy To QA'
  variables:
  - template: variables/qa.yml
  
  jobs:
  - template: deploymentJob.yml
