parameters:
- name: counter
  displayName: Counter
  type: number
  default: 5

jobs:
- job: generate
  steps:
  - checkout: none
  - bash: |
      echo "##vso[task.setVariable variable=param;isOutput=true]{'a':{'myvar':'A'}, 'b':{'myvar':'B'}}"
    name: mtrx
    
- job: build
  dependsOn: generate
  strategy:
    matrix: $[ dependencies.generate.outputs['mtrx.param'] ]    
  steps:
  - checkout: none
  - script: echo $(value)
