trigger: none

parameters:
- name: counter
  displayName: Counter
  type: number
  default: 5

jobs:
- job: generate
  steps:
  - checkout: none
  - bash: |
      temp=""
      for i in {1..5} 
      do 
        temp+="\"Param_$i\": {\"value\": $i}, "
      done
      temp="{$temp}"
      echo "##vso[task.setVariable variable=param;isOutput=true]$temp"
    name: mtrx
    
- job: build
  dependsOn: generate
  strategy:
    matrix: $[ dependencies.generate.outputs['mtrx.param'] ]    
  steps:
  - checkout: none
  - script: echo $(value)
  - template: template.yml
    parameters:
      param: $(value)
