resources:
  repositories:
    - repository: self
      type: github
      trigger:
        branches:
          include:
          - master
    - repository: second
      type: github
      name: vijayma/second-repo
      endpoint: vijayma
      trigger:
        branches:
          include:
            - master

steps:
- script: echo hello world