resources:
  repositories:
    - repository: self
      type: git
      trigger:
        branches:
          include:
          - master
    - repository: second
      type: git
      name: second-repo

steps:
- script: echo hello world

    