trigger: none

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - script: echo Build

- stage: Test
  jobs:
  - job: Test
    steps:
    - script: echo Test
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'qaConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az group list --query "[?location==''westus'']"'
    

- stage: Prod
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: Prod
    steps:
    - script: echo Prod
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Build_Eng(3f56da7f-5953-4018-8ca8-e20dbfa0a7e2)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az group list --query "[?location==''westus'']"'
