trigger: none

schedules:
- cron: "*/10 * * * *"
  displayName: S1
  branches:
    include:
    - master
- cron: "*/12 * * * *"
  displayName: S2
  branches:
    include:
    - master

steps:
- ${{ if eq(variables['Build.Reason'], 'Schedule') }}:
  - script: echo "Scheduled"
- ${{ if eq(variables['Build.Reason'], 'Manual') }}:
  - script: echo "Manual"

