parameters:
- name: jobs
  type: object
  
jobs:
- ${{ each job in parameters.jobs }}:
  - ${{ each pair in job }}:
      ${{ if ne(pair.key, 'steps') }}:
        ${{ pair.key }}: ${{ pair.value }}

- job: extrajob
  dependsOn:
  - ${{ each job in parameters.jobs }}:
      - ${{ job.job }}
  steps:
  - script: echo extra step
